### ISSUE TITLE
improve buy strategy

### ISSUE THREAD

**Issue by ferater** [froggleston/cryptofrog-strategies#5]
Hello,
maybe you can use MOST to make buy strategy better.
There is a link here, if you want to see : [https://github.com/freqtrade/technical/issues/90](url)
and MOST official link is here: [https://tr.tradingview.com/script/28ZcW4nv/](url)

**Comment by froggleston** [comment]
By all means implemet these in the strategy in a fork. I'm not putting much work into this at the moment.
